version: '3.8'
services:
  chronos:
    build: .
    container_name: chronos_vehicle
    cap_add:
      - NET_ADMIN
    shm_size: '2gb'
    ports:
      - "6901:6901" # Kasm VNC
      - "5000:5000" # Optional: temporal controller (use only on trusted VPS)
    env_file:
      - .env
    environment:
      - VNC_PW=password123
    restart: always
    volumes:
      - ./app/time_control:/app/time_control
    security_opt:
      - no-new-privileges:true
